import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="fixed hidden md:block w-64 top-0 bottom-0 shadow-r bg-white p-4">
          <Link href="/">
            <img
              className="w-36"
              src="https://accounts.byteark.com/assets/logo/byteark-logo-full-dark.png"
            />
          </Link>
        </div>
        <div className="md:ml-64">{children}</div>
      </body>
    </html>
  );
}
